### ISSUE TITLE
Add translation capability

### ISSUE THREAD

**Issue by NathanBnm** [aggalex/Wineglass#30]
I'm able to add French translations

**Comment by aggalex** [comment]
Omg, I totally said that I was going to do it when I finished the app and then I just mindlessly tried to upload to AppCenter. Thank god this app doesn't have a lot to translate.

**Comment by aggalex** [comment]
So, I added translation capability, now everything is in place. I don't really know how translations are usually suggested, so, could you please help me on that? ;)

**Comment by NathanBnm** [comment]
Great! I will propose French translations.

I don't really now what you prefer, but usually elementary developers just put the translation button in appdata.xml file which redirects to the po director. Maybe you have to include a README file there.

Then people submit their translations via Pull Requests.

Just take a look on other apps!

**Comment by aggalex** [comment]
Got it! Thanks for contributing to my project! Can't wait for your pull request.

**Comment by NathanBnm** [comment]
Here it is @aggalex #36
