### ISSUE TITLE
Make the app more translator-friendly.

### ISSUE THREAD

**Issue by aggalex** [aggalex/Wineglass#35]
1. Create a "translating" wiki page
2. Add a "Suggest Translations" Button

Edit: Me and my idiocy...

**Comment by NathanBnm** [comment]
Don't forget to add the translation button into the  `appdata.xml` file like this
```xml
<url type="translate">https://github.com/aggalex/Wineglass/tree/master/po</url>
```

**Comment by aggalex** [comment]
The wiki page is not really necessary, and the button seems to be there. I'm closing this...
