### ISSUE TITLE
Add some missing strings

### ISSUE THREAD

**Issue by NathanBnm** [aggalex/Wineglass#38]
I think it will easier for people if you add hover titles on the '+' button in the header-bar and on the trash button like 'Create a new empty wineprefix' and 'delete wineprefix'.

**Comment by aggalex** [comment]
Great idea! Will doo when I have the time.

**Comment by NathanBnm** [comment]
Yes you're right!

**Comment by aggalex** [comment]
Did it! would you please translate my new tooltips?

**Comment by NathanBnm** [comment]
@aggalex yes sure!
