### ISSUE TITLE
Use gender-neutral language in app description.

### ISSUE THREAD

**Issue by lewisgoddard** [aggalex/Wineglass#39]
> Wineglass is a small application that allows the user to manage **his** wineprefixes easily and install windows programs without the need of the terminal. [...]

should probably be

> Wineglass is a small application that allows the user to manage **their** wineprefixes easily and install windows programs without the need of the terminal. [...]

**Comment by aggalex** [comment]
You're right, I will do that when I upload the next release, which, alas, might be a little late, since I'm very busy lately...

**Comment by aggalex** [comment]
fixed!
