### ISSUE TITLE
Add task manager to the prefix menu

### ISSUE THREAD

**Issue by sprite-1** [aggalex/Wineglass#44]
I'm referring to this menu

![image](https://user-images.githubusercontent.com/33685433/57072314-deb74300-6d0f-11e9-9e25-96fbf79c9350.png)

**Comment by aggalex** [comment]
I didn't know wine had a task manager. Anyways, I'm currently on fire studying fo the uni, I'll do it eventually though.

**Comment by sprite-1** [comment]
Thanks @aggalex, good luck with uni! This is what the task manager looks like

![image](https://user-images.githubusercontent.com/33685433/57156117-c4648e80-6e0f-11e9-98b5-364faf8ef574.png)

It even also has its own file explorer

![image](https://user-images.githubusercontent.com/33685433/57156178-e52ce400-6e0f-11e9-8511-085511b09a56.png)
