### ISSUE TITLE
chat gets closed when swiping up or down in telegram

### ISSUE THREAD

**Issue by ranjith35333** [aggalex/Wineglass#46]

**Comment by aggalex** [comment]
Um, what do you mean? This is wineglass not telegram... Wineglass is merely a GUI for Wine, if you tried to run Telegram for windows in wineglass and it crashed it most probably isn't wineglass' fault (all Wineglass does is facilitate the installation and maintenance of a Windows program through Wine, not run it), but Wine's fault, please report this issue to the Wine devs.
